shellcheck defensiveness in statmygits

diff --git a/statmygits b/statmygits
--- a/statmygits
+++ b/statmygits
@@ -29,6 +29,7 @@ while getopts $options opt; do case $opt in
     *) printf >&2 "Unknown option '%s', ignoring\n" "${opt}" ;;
 esac; done
 shift $((OPTIND - 1))
+# shellcheck disable=SC2164 # cd should never fail, target dir has been checked
 [[ $# -eq 1 && -d "$1" ]] && cd "$1"
 
 # are we doing a specific directory, or all?
@@ -43,7 +44,7 @@ if [[ ${#SOURCES[@]} -eq 0 ]]; then
     # we are doing all of them....
     # first, make sure we can find one and only one of each one
     for targetDir in "${!TARGET_DIRS[@]}"; do
-        possibleDir=$(find ~ -xdev -type d -name ${targetDir} -print 2> /dev/null)
+        possibleDir=$(find ~ -xdev -type d -name "${targetDir}" -print 2> /dev/null)
         dirCount=$(echo "${possibleDir}" | wc -l)
         if [[ $dirCount -ne 1 ]]; then
             printf >&2 "For '%s', wanted one targetDir, got %s, skipping\n" "${targetDir}" "${dirCount}"
@@ -77,7 +78,7 @@ diffColorOption () {
 
 replaceOrSwap () {
     anyDiffs=yes
-    diff $(diffColorOption) -u ${targetDir}/${file} ${sourceDir}/${file}
+    diff "$(diffColorOption)" -u "${targetDir}/${file}" "${sourceDir}/${file}"
     echo; echo "If + is wanted, 'y'; if - is wanted, 'swap'; 'd' deletes '-'; otherwise, anything else."
     read -r -p "Replace $file in ~? " answer
     case $answer in
@@ -88,7 +89,7 @@ replaceOrSwap () {
             replace
             ;;
         d)
-            rm ${targetDir}/${file}
+            rm "${targetDir}/${file}"
             ;;
         *)
             :
@@ -97,11 +98,11 @@ replaceOrSwap () {
 }
 
 replace () {
-    cp -p ${targetDir}/${file} ${sourceDir}/${file} || printf >&2 "Error copying!!!\n"
+    cp -p "${targetDir}/${file}" "${sourceDir}/${file}" || printf >&2 "Error copying!!!\n"
 }
 
 makeOrUpdate () {
-    cp -p ${sourceDir}/${file} ${targetDir}/${file} || printf >&2 "Error copying!!!\n"
+    cp -p "${sourceDir}/${file}" "${targetDir}/${file}" || printf >&2 "Error copying!!!\n"
 }
 
 addMissing () {
@@ -111,7 +112,7 @@ addMissing () {
         doIt="yes"
     else
         echo "The file '${targetDir}/${file}' does not exist;"
-        read -p "createit from '${sourceDir}/${file}'? " answer
+        read -r -p "createit from '${sourceDir}/${file}'? " answer
         case $answer in
             y*|Y*)
                 doIt="yes"
@@ -128,11 +129,10 @@ gitStatus () {
     local dir=""
     [[ $# -eq 1 ]] && dir="${1}"
     if [[ $dir ]]; then
-        local gitStat=""
-        if git -C $dir status &> /dev/null; then
-            git -C $dir status
+        if git -C "$dir" status &> /dev/null; then
+            git -C "$dir" status
         else
-            (cd $dir && git status)
+            (cd "$dir" && git status)
         fi
     fi
 
@@ -144,7 +144,7 @@ for sourceDir in "${SOURCES[@]}"; do
     case $baseDir in
         myBinFiles)
             if [[ ! -f $targetDir ]]; then
-                mkdir -p $targetDir
+                mkdir -p "$targetDir"
             fi
             DOVIM=""
             ;;
@@ -155,7 +155,7 @@ for sourceDir in "${SOURCES[@]}"; do
     # are we actually in the sourceDir?
     foundManifest=""
     for possibleSourceDir in "${sourceDir}" ~/"${sourceDir}" ~/"myPlumbing/${sourceDir}"; do
-        possibleSourceDir=$(realpath ${possibleSourceDir})
+        possibleSourceDir=$(realpath "${possibleSourceDir}")
         theManifest="${possibleSourceDir}/${MANIFEST}"
         [[ ! -f ${theManifest} || ! -s ${theManifest} ]] && continue
         foundManifest="yes" && break
@@ -166,6 +166,7 @@ for sourceDir in "${SOURCES[@]}"; do
     (
         # this sets fileManifest
         # this also sets hardLinkedFiles
+        # shellcheck disable=SC1090
         source "${theManifest}" || { printf >&2 "Cannot source '%s', exiting.\n" "${theManifest}"; exit 7; }
 
         anyDiffs=no
@@ -173,34 +174,34 @@ for sourceDir in "${SOURCES[@]}"; do
             if [[ ! -f ${targetDir}/${file} ]]; then
                 addMissing
             else
-                if ! diff -q ${targetDir}/${file} ${sourceDir}/${file} 2> /dev/null; then
+                if ! diff -q "${targetDir}/${file}" "${sourceDir}/${file}" 2> /dev/null; then
                     replaceOrSwap
                 fi
             fi
             if [[ -f ${targetDir}/${file} && ${hardLinkedFiles[$file]:+IS_SET} ]]; then
                 for linkToMake in ${hardLinkedFiles[$file]}; do
-                    hardLinks+=(${linkToMake})
-                    rm -f ${targetDir}/${linkToMake}
-                    ln ${targetDir}/${file} ${targetDir}/${linkToMake} || >&2 printf "Could not create link from '%s' to '%s'\n" ${targetDir}/${file} ${targetDir}/${linkToMake}
+                    hardLinks+=("${linkToMake}")
+                    rm -f "${targetDir}/${linkToMake}"
+                    ln "${targetDir}/${file}" "${targetDir}/${linkToMake}" || >&2 printf "Could not create link from '%s' to '%s'\n" "${targetDir}/${file}" "${targetDir}/${linkToMake}"
                 done
             fi
         done
 
-        [[ ${anyDiffs} == no ]] && { printf >&2 "No diffs, no need to change anything.\n"; gitStatus $sourceDir ; } || true
+        [[ ${anyDiffs} == no ]] && { printf >&2 "No diffs, no need to change anything.\n"; gitStatus "$sourceDir" ; }
 
         if [[ $baseDir == "myBinFiles" ]]; then
             declare -a extras=()
             while read -r; do
                 file=$(basename "$REPLY")
                 [[ -f $sourceDir/$file ]] && continue
-                for linkFile in ${hardLinks[@]}; do
+                for linkFile in "${hardLinks[@]}"; do
                     [[ ${file} == "${linkFile}" ]] && continue 2
                 done
-                extras+=($file)
+                extras+=("$file")
             done < <(ls "${targetDir}")
             [[ ${#extras[@]} -gt 0 ]] && printf "Extras:\t"
             for file in "${extras[@]}"; do
-                printf "%s " $file
+                printf "%s " "$file"
             done
             [[ ${#extras[@]} -gt 0 ]] && printf "\n"
         fi
@@ -208,7 +209,7 @@ for sourceDir in "${SOURCES[@]}"; do
 
     if [[ $DOVIM ]]; then
         if type ${VIMPLUGS} &> /dev/null; then
-            ${VIMPLUGS} ${sourceDir}/${VIMPACKS}
+            ${VIMPLUGS} "${sourceDir}/${VIMPACKS}"
         else
             printf >&2 "Update bin files first, please\n"
             exit 1
