Complete commit a115deb after on-box testing

diff --git a/statmygits b/statmygits
--- a/statmygits
+++ b/statmygits
@@ -8,10 +8,10 @@ VIMPACKS="vimpacks"
 MANIFEST="manifest"
 DOVIM=""
 NODOVIM=""
-declare -A DO_DIRS
-DO_DIRS[myBinFiles]=~/bin
-DO_DIRS[myDotFiles]=~
-declare -a DO_THESE=()
+declare -A SOURCE_DIRS
+SOURCE_DIRS[myBinFiles]=~/bin
+SOURCE_DIRS[myDotFiles]=~
+declare -a SOURCES=()
 
 init=""
 while getopts iV opt; do case $opt in
@@ -26,25 +26,25 @@ shift $((OPTIND - 1))
 # first, check our cwd to determine if specific
 myDir=$(pwd)
 baseDir=$(basename "${myDir}")
-for dir in "${!DO_DIRS[@]}"; do
-    [[ $baseDir == "$dir" ]] && { DO_THESE+=("$myDir"); break; }
+for sourceDir in "${!SOURCE_DIRS[@]}"; do
+    [[ $baseDir == "$sourceDir" ]] && { SOURCES+=("$myDir"); break; }
 done
 
-if [[ ${#DO_THESE[@]} -eq 0 ]]; then
+if [[ ${#SOURCES[@]} -eq 0 ]]; then
     # we are doing all of them....
     # first, make sure we can find one and only one of each one
-    for dir in "${!DO_DIRS[@]}"; do
-        possibleDir=$(find ~ -xdev -type d -name "${dir}" -print 2> /dev/null)
+    for sourceDir in "${!SOURCE_DIRS[@]}"; do
+        possibleDir=$(find ~ -xdev -type d -name ${sourceDir} -print 2> /dev/null)
         dirCount=$(echo "${possibleDir}" | wc -l)
         if [[ $dirCount -ne 1 ]]; then
-            printf >&2 "For '%s', wanted one dir, got %s, skipping\n" "${dir}" "${dirCount}"
+            printf >&2 "For '%s', wanted one sourceDir, got %s, skipping\n" "${sourceDir}" "${dirCount}"
             continue
         fi
-        DO_THESE+=("$possibleDir")
+        SOURCES+=("$possibleDir")
     done
 fi
 
-# DO_THESE is set to one or more directories to be processed;
+# SOURCES is set to one or more directories to be processed;
 # carry on....
 
 diffColorOption () {
@@ -57,7 +57,7 @@ diffColorOption () {
 
 replaceOrSwap () {
     anyDiffs=yes
-    diff $(diffColorOption) -u ${compareWith}/${file} ${dir}/${file}
+    diff $(diffColorOption) -u ${target}/${file} ${sourceDir}/${file}
     echo; echo "If + is wanted, 'y'; if - is wanted, 'swap'; 'd' deletes '-'; otherwise, anything else."
     read -p "Replace $file in ~? " answer
     case $answer in
@@ -68,7 +68,7 @@ replaceOrSwap () {
             replace
             ;;
         d)
-            rm ${compareWith}/${file}
+            rm ${target}/${file}
             ;;
         *)
             :
@@ -77,11 +77,11 @@ replaceOrSwap () {
 }
 
 replace () {
-    cp -p ${compareWith}/${file} ${dir}/${file} || printf >&2 "Error copying!!!\n"
+    cp -p ${target}/${file} ${sourceDir}/${file} || printf >&2 "Error copying!!!\n"
 }
 
 makeOrUpdate () {
-    cp -p ${dir}/${file} ${compareWith}/${file} || printf >&2 "Error copying!!!\n"
+    cp -p ${sourceDir}/${file} ${target}/${file} || printf >&2 "Error copying!!!\n"
 }
 
 addMissing () {
@@ -90,8 +90,8 @@ addMissing () {
     if [[ $init == "yes" ]]; then
         doIt="yes"
     else
-        echo "The file '${compareWith}/${file}' does not exist;"
-        read -p "createit from '${dir}/${file}'? " answer
+        echo "The file '${target}/${file}' does not exist;"
+        read -p "createit from '${sourceDir}/${file}'? " answer
         case $answer in
             y*|Y*)
                 doIt="yes"
@@ -118,13 +118,13 @@ gitStatus () {
 
 }
 
-for dir in "${DO_THESE[@]}"; do
-    baseDir=$(basename "${dir}")
-    compareWith=${DO_DIRS[$baseDir]}
+for sourceDir in "${SOURCES[@]}"; do
+    baseDir=$(basename "${sourceDir}")
+    target=${SOURCE_DIRS[$baseDir]}
     case $baseDir in
         myBinFiles)
-            if [[ ! -f $compareWith ]]; then
-                mkdir -p $compareWith
+            if [[ ! -f $target ]]; then
+                mkdir -p $target
             fi
             DOVIM=""
             ;;
@@ -132,8 +132,8 @@ for dir in "${DO_THESE[@]}"; do
             [[ ! $NODOVIM ]] && DOVIM="yes"
             ;;
     esac
-    theManifest="${dir}/${MANIFEST}"
-    [[ ! -f ${theManifest} || ! -s ${theManifest} ]] && { printf >&2 "No manifest, very odd, skipping '%s'.\n" "${dir}"; continue; }
+    theManifest="${sourceDir}/${MANIFEST}"
+    [[ ! -f ${theManifest} || ! -s ${theManifest} ]] && { printf >&2 "No manifest, very odd, skipping '%s'.\n" "${sourceDir}"; continue; }
 
     (
         # this sets fileManifest
@@ -142,27 +142,27 @@ for dir in "${DO_THESE[@]}"; do
 
         anyDiffs=no
         for file in $fileManifest; do
-            if [[ ! -f ${compareWith}/${file} ]]; then
+            if [[ ! -f ${target}/${file} ]]; then
                 addMissing
             else
-                if ! diff -q ${compareWith}/${file} ${dir}/${file} 2> /dev/null; then
+                if ! diff -q ${target}/${file} ${sourceDir}/${file} 2> /dev/null; then
                     replaceOrSwap
                 fi
             fi
-            if [[ -f ${compareWith}/${file} && ${hardLinkedFiles[$file]:+IS_SET} ]]; then
-                for linkToMake in "${hardLinkedFiles[$file]}"; do
-                    rm -f ${compareWith}/${linkToMake}
-                    ln ${compareWith}/${file} ${compareWith}/${linkToMake}
+            if [[ -f ${target}/${file} && ${hardLinkedFiles[$file]:+IS_SET} ]]; then
+                for linkToMake in ${hardLinkedFiles[$file]}; do
+                    rm -f ${target}/${linkToMake}
+                    ln ${target}/${file} ${target}/${linkToMake} || >&2 printf "Could not create link from '%s' to '%s'\n" ${target}/${file} ${target}/${linkToMake}
                 done
             fi
         done
 
-        [[ ${anyDiffs} == no ]] && { printf >&2 "No diffs, no need to change anything.\n"; gitStatus $dir ; } || true
+        [[ ${anyDiffs} == no ]] && { printf >&2 "No diffs, no need to change anything.\n"; gitStatus $sourceDir ; } || true
     )
 
     if [[ $DOVIM ]]; then
         if type ${VIMPLUGS} &> /dev/null; then
-            ${VIMPLUGS} ${dir}/${VIMPACKS}
+            ${VIMPLUGS} ${sourceDir}/${VIMPACKS}
         else
             printf >&2 "Update bin files first, please\n"
             exit 1
